### ISSUE TITLE
Criar o relacionamento do Solicitacao com o Segmento nas Classes

### ISSUE THREAD

**Issue by marcelosilva7** [B1nary-Devs/JAIA-SOFTWARE#155]
- [ ] Criar o relacionamento do Solicitacao com o Segmento nas Classes

**Comment by GuiAlvesdev** [comment]
waiting for creation class Solicitacao

**Comment by GuiAlvesdev** [comment]
finish create relation segmento and solicitacao 
![image](https://github.com/B1nary-Devs/JAIA-SOFTWARE/assets/72584502/7c3f17e1-f863-49fb-ad86-d93a1f7a9f67)
