### ISSUE TITLE
Criar da classe Categoria 

### ISSUE THREAD

**Issue by marcelosilva7** [B1nary-Devs/JAIA-SOFTWARE#30]
Criação da Criação da classe Categoria realizando as seguintes tasks:
- [x] Criação do Model
- [x] Criação do Repository
- [x] Criação do Service
- [x] Criacao do Controller
- [x] Criacao do Relacionamento com a Classe CheckList

**Comment by GuiAlvesdev** [comment]
finalizado categoria e metodos post,findall, delete
